*** Tools common for all OSs

**** IDEs : 

- Eclipse (Optional Plugins : TestNG, EclEmma Code Coverage, Spring Tools 4) 
- IntelliJ Idea (Probably don't need Visual Studio Code if we have this) One of the cons of this is, this is very memory intensive.
- Visual Studio Code :
	- Themes: 
		- azure (nice theme but it doesn't apply to file menu on the left)
		- light theme (I like to use it in daylight),
		- GitHub Theme (nice theme that applies to file menu on the left)
	- Plugins: 
		- haskell-linter
		- Haskell Syatax Highlighting
		- Open in Vim (if working with Vim is not possible)
		- Vim plugin for Visual Studio Code (this cuts down the pain of setting up something like Emacs)
		- Markdown preview (Use ghostwriter instead of this if possible)
	- Customizations:
		- To remove the sideview bar (called the minimap), set "editor.minimap.enabled": false in your user or workspace settings.

**** Text editors

1. Vim
2. gVim

**** Browsers

1. Firefox(lastpass, instapaper, Dark Reader)
2. Tor browser

**** Miscellaneous

Calibre ebook editor and viewer

*** Windows

- Git + Good git interface for Windows

- Text editors : 
  - Notepad++ - plugins: Compare plugin,XML tools plugin, 

- 7 zip

- Console Emulation program - ConEmu

*** Linux

- Git + Good git interface for Linux - 
  - If we can work with Vim and vim-fugitive, that, when used along with terminal, should be enough for pretty much everything related to Git.
  - gitg (lighter and faster - lets us stage individual lines and chunks)
  - GitAhead (Good tool to understand the history. Did not use it very extensively though. Can it be helpful with resolving merge conflicts and rebasing? Have to use it with bigger projects to figure that out.)
  - Eclipse eGit plugin is probably the best. It works the same way in all OSs and it has all the features we really need.
- Ghostwriter - good editor to work with markdown files. Formats them exactly the way github expects. One problem that I noticed with this app is, if you open a file in it, and make changes to that file using some other app at the same time (like Vim, VS Code, etc.) and save the changes to the file there, those changes are not reloaded into Ghostwriter automatically. What is worse is, as soon as the file is closed in Ghostwriter, the changes made to the file (using the other apps) are reverted. All those changes are lost. This is a bad use case. This app is good for looking at files and making changes to files but it is not great at working with other apps simultaneously. In order to get around these issues, use it to view markdown files but not to make changes to them. Use something else for making changes to the files and use ghostwriter only to view the markdown preview.
- Broot (Directory navigators) - if you are not sure where in the file system a given file is, Broot will be very helpful in that scenario because it can scan the entire file system and show the location of the file to you.
- File managers
  - Thunar (works very well. no other file managers are really necessary if we have this.)
  - PCManFM (not really necessary if you already have Thunar)
  - Vifm is a curser based vi[m] like file manager extended with some useful ideas from mutt. If you use vi[m], vifm gives you complete keyboard control over your files without having to learn a new set of commands. It goes not just about vi[m] like keybindings, but also about modes, options, registers, commands and other things you might already like in vi[m].
- System Monitors
  - HTop  
- Screenshot utility
  - Flameshot (never used)
- Office suites
  - Libre office (This works for most of the scenarios. If we have this, no other office suite is necessary.)
  - Open office (never used)
  - Calligra (never used)
  - wps office? (used - the interface is good. But support for fonts is not as good as that of LibreOffice? Some fonts were totally unreadable)
- img2pdf (to convert images into pdf documents) - (usage: in terminal: $ img2pdf img1.png img2.jpg -o out.pdf) (img2pdf --help)
- pdf arranger (to work with pdf documents - joining multiple pdf documents into one)
- GNU web browser - to keep firefox and regular surfing separate (Chromium is an alternative to this).
- Variety (Nitrogen is an alternative) - wallpaper utility tool. Generally, there are great wallpapers on unsplash.com. There is an option in Variety's preferences to pull wallpapers from unsplash.
- USB Stick Formatter
- USB Image Writer

*** Android (alphabetical order)

- APAS (Algorithm Problems and Solutions)
- Algorithms (visual explanation)
- Alltrails
- Authenticator (Microsoft)
- Dropbox (optional)
- DuckDuckGo
- Fairmail (using this for Gmail and hotmail accounts right now)
- Firefox (extensions - Dark Reader)
- Foxit PDF Reader (for pdf files)
- GPS Tools
- Geeks for Geeks
- GitHub
- Glassdoor (Job search) Is there an app for indeed?
- Instapaper (Reading)
- Lastpass
- LinkedIn (Job search) (Not using it all that much)
- Mapquest (maps)
- Mega Sync Client
- Messenger (Facebook) (Messaging apps)
- Moonreader (This has good support for txt and markdown files along with epub, mobi and a lot of other file types. A very good app.)
- NetGuard
- OsmAnd (maps)
- Outlook (Microsoft) (For FusionAlliance Webmail and hotmail accounts - might also work for Gmail and other accounts) (Email client)
- Podcasts (Google) (Podcasts)
- Quora	 (Reading)
- Spotify (Music)
- Sync (cloud client)
- The weather channel (weather)
- Tor Browser (browser)
- Tutanota (Email client)
- Udemy
- Vim Master
- Walldrobe (wallpapers from Unsplash)
- Whatsapp (Messaging apps)
- Word (Microsoft) (for word files)
- WriterP (simple text editor)
- Yahoomail (good with Yahoo accounts - if this cannot be set up in other email clients - can we set it up in Microsoft Outlook app?) (Email client)
- Youtube

-----------------------------------------------------------------------------------------

*** How to use multiple workspaces

This is useful in both Windows and Linux. This makes the workflow so much easier than switching between windows in a single workspace. Using keyboard shortcuts make this even better. 

Hold down Ctrl + Alt and tap an arrow key to 
quickly move up, down, left, or right between workspaces, 
depending on how they’re laid out. 

Add the Shift key—so, press Shift + Ctrl + Alt and 
tap an arrow key—and you’ll switch between workspaces, 
taking the currently active window with you to the new workspace.

**** Multiple workspaces in Windows

    1. How to add a desktop in Windows 10:
       To add a virtual desktop, open up the new Task View pane by clicking the Task View button (two overlapping rectangles) on the taskbar, or by pressing the Windows Key + Tab. In the Task View pane, click New desktop to add a virtual desktop. If you have two or more desktops already open, the "Add a desktop" button will appear as a gray tile with a plus symbol. You can also quickly add a desktop without entering the Task View pane by using the keyboard shortcut Windows Key + Ctrl + D.

    2. How to switch between desktops:
       To switch between virtual desktops, open the Task View pane and click on the desktop you want to switch to. You can also quickly switch desktops without going into the Task View pane by using the keyboard shortcuts Windows Key + Ctrl + Left Arrow and Windows Key + Ctrl + Right Arrow.

    3. Move windows between desktops:
       To move a window from one desktop to another, you first have to open up the Task View pane and then hover over the desktop containing the window you want to move. The windows on that desktop will pop up; find the window you want to move, right-click it, and go to Move to and choose the desktop you want to move the window to. You can also drag and drop windows -- grab the window you want to move and drag it into the desired desktop.

    4. Close a desktop:
       To close a virtual desktop, open up the Task View pane and hover over the desktop you want to close until a small X appears in the upper right corner. Click the X to close the desktop. You can also close desktops without going into the Task View pane by using the keyboard shortcut Windows Key + Ctrl + F4 (this will close the desktop you're currently on).

-----------------------------------------------------------------------------------------

*** Ready API/Soap UI preferences

UI - Workspace type : Tabbed Desktop

ReadyAPI - Default SOAP request editor : XML
           Default REST request editor : Request
           Default response editor : XML

-----------------------------------------------------------------------------------------

*** Android alternatives

GrapheneOS
LineageOS (supports many older devices)

-----------------------------------------------------------------------------------------

*** Wizdler

Parses the WSDL files and generates SOAP messages for you # Wizdler

Recognizes WSDL information on the page to show you the available services and operations. Click the operation to generate the SOAP requests and view the response. By clicking the service, you can download WSDL and external XSD files in single ZIP file.

-----------------------------------------------------------------------------------------

*** OpenAPI spec editing tools

Swagger YAML editing tool : http://editor.swagger.io/

use this to generate server code and client code as well.

Stoplight studio is another good one. 

-----------------------------------------------------------------------------------------

*** Putty

   change password : `passwd`
 
-----------------------------------------------------------------------------------------

*** Calibre book-reader customization

   In order to increase line spacing in paragraphs:

   Preferences -> User Stylesheet -> p {line-height: 2}
 
-----------------------------------------------------------------------------------------

*** Command to put computer to sleep

    Windows:
    
      #+BEGIN_EXAMPLE
      rundll32.exe powrprof.dll,SetSuspendState 0,1,0
      #+END_EXAMPLE

-----------------------------------------------------------------------------------------

*** Mouse issues in Windows

    Mouse cursor disappears in any dialogue or text box or document : 
    
    If you want to change it to a larger one :
    Control Panel -> Large icons -> Mouse -> Pointers -> Normal Select -> Browse -> aero_arrow.cur (or any other one that you like)
    Control Panel -> Large icons -> Mouse -> Pointers -> Text Select -> Browse -> aero_arrow.cur (or any other one that you like)
    
    a. Open Control Panel. 
    b. In View by: Large icon view, click on Mouse.
    c. Click the Pointer options tab and uncheck Hide pointer while typing.
    d. Click on Apply and check the issue.

-----------------------------------------------------------------------------------------

*** Lenovo Thinkpad tips

    How do you turn on the light on top of the monitor?
    
    To turn on the small light on the top of the monitor (when working in the dark and it is very difficult to see the keyboard) `Fn + PgUp` should do it.

-----------------------------------------------------------------------------------------

*** Windows VDEs running out of memory

Hi all, the C drive in one of my VDE slices seems to be running out of memory. 
It came with 50 GB initially and now it has just about 100MB memory available in it. 
I freed up some space by uninstalling some of the programs I was not using all that often and that freed up about 1 GB of space in the C drive but all that free space quickly got filled up by some processes running in the background. 
I submitted a request for 'clean up C drive' but that seems to have failed - twice. 
I cannot do anything with that slice because of the lack of available memory. 
I requested a new slice but I am trying to understand what it is that went wrong with it. 
Did any of you see this happen in the past?

Download WizTree on your slice, it'll tell you where all of your space is being used up.

By using this tool, after determining that 'C:\Windows\ccmcache' is the folder taking up all the space,

The ccmcache folder is used by System Center Configuration Manager (SCCM) client. This is where files downloaded by SCCM are stored. SCCM is an enterprise software management system used in many Windows environment, and provides operating system and software deployment services, remote management, reporting services, etc. You will typically only find this folder on systems in a managed enterprise environment.
SCCM caches files used for software deployment in the ccmcache folder. This may include software packages which are automatically installed on your machine, some types of software updates, etc. Files are not automatically removed from the ccmcache folder after they are used, but they are marked as being eligible for deletion. You should not manually delete files in this folder as you may accidentally delete something which has not been used yet. You should definitely not remove the folder altogether, as this would break SCCM and you would cease to automatically receive software packages from your network administrator.
You should be able to reduce the size of this folder using the ConfigMgr Control Panel. This will require local administrator privileges. To do this:
Open "Configuration Manager Properties" in the control panel. You may need to change the control panel to "icon view" instead of "category view".
Go to the "cache" tab
Click "Configure Settings" and acknowledge the UAC Prompt if prompted
The "Delete Files" button should become available. Click this button to clear files. It will automatically keep any files which should not be deleted.

-----------------------------------------------------------------------------------------
