*** Tools for Android (alphabetical order)

- APAS (Algorithm Problems and Solutions)
- Algorithms (visual explanation of algorithms)
- Alltrails (optional)
- Amazon Prime Video (streaming)
- Authenticator (Microsoft)
- BlipBlip (blip reminder on an hourly or timely basis)
- +Cambridge Dictionary+
- Chess.com
- +DuckDuckGo+
- Fairmail (using this for Gmail and hotmail accounts right now)
- +Fdroid+
- Firefox (extensions - Dark Reader) (set startpage.com as the default search engine)
- GPS Tools (good app with various features to determine gps info)
- +Geeks for Geeks+
- GitHub (Preferable to look at repositories in a browser. The app is not all that helpful)
- +Glassdoor (Job search)+
- HBO Max (streaming)
- Instapaper (Reading articles)
- +LBRY+
- Lastpass (password manager)
- +LinkedIn (Job search)+
- +Mapquest+ (maps)
- Mega Sync Client
- Moonreader (This has good support for txt and markdown files along with epub, mobi and a lot of other file types. A very good app. Use this for pdfs as well. You do not need any other app specifically for pdfs.)
- NetGuard
- Netflix (streaming)
- OpenPhone (optional)
- +OsmAnd+
- Outlook (Microsoft) (For FusionAlliance Webmail and hotmail accounts - might also work for Gmail and other accounts) (Email client)
- Podcasts (Google) (Podcasts)
- +Quora (Reading) - Beware of this. This could turn out to be a time pit. You are probably better off logging into the website in a computer when necessary+
- Signal (Messaging apps)
- Spotify (Music)
- +Startpage search engine app+
- Sync (cloud client)
- The weather channel (weather)
- Tor Browser (browser) (set startpage.com as the default search engine)
- Tutanota (Email client)
- Udemy (optional)
- +Vim Master+
- Walldrobe (wallpapers from Unsplash)
- Whatsapp (Messaging apps)
- +Word (Microsoft) (technically, it supports pdf files as well. But it is very slow. Moonreader seems to be much faster alternative to this.)+
- WriterP (simple text editor)
- Yahoomail (good with Yahoo accounts - if this cannot be set up in other email clients - can we set it up in Microsoft Outlook app?) (Email client)
- Youtube


