*** Tools common for all OSs

**** IDEs : 

- Eclipse (Optional Plugins : TestNG, EclEmma Code Coverage, Spring Tools 4) 
- Visual Studio Code (see the file for it for details)
- IntelliJ Idea - Try and stay away from this. This is very resource intensive.

**** Text editors

1. Vim
2. gVim

**** Browsers

1. Firefox(lastpass, instapaper, Dark Reader)
2. Tor browser

**** Miscellaneous

Calibre ebook editor and viewer

*** Tools for Windows

- Git + Good git interface for Windows

- Text editors : 
  - Notepad++ - plugins: Compare plugin,XML tools plugin, 

- 7 zip

- Console Emulation program - ConEmu

*** Tools for Linux

- Git + Good git interface for Linux - 
  - If we can work with Vim and vim-fugitive, that, when used along with terminal, should be enough for pretty much everything related to Git.
  - gitg (lighter and faster - lets us stage individual lines and chunks)
  - GitAhead (Good tool to understand the history. Did not use it very extensively though. Can it be helpful with resolving merge conflicts and rebasing? Have to use it with bigger projects to figure that out.)
  - Eclipse eGit plugin is probably the best. It works the same way in all OSs and it has all the features we really need.
- Ghostwriter - good editor to work with markdown files. Formats them exactly the way github expects. One problem that I noticed with this app is, if you open a file in it, and make changes to that file using some other app at the same time (like Vim, VS Code, etc.) and save the changes to the file there, those changes are not reloaded into Ghostwriter automatically. What is worse is, as soon as the file is closed in Ghostwriter, the changes made to the file (using the other apps) are reverted. All those changes are lost. This is a bad use case. This app is good for looking at files and making changes to files but it is not great at working with other apps simultaneously. In order to get around these issues, use it to view markdown files but not to make changes to them. Use something else for making changes to the files and use ghostwriter only to view the markdown preview.
- Broot (Directory navigators) - if you are not sure where in the file system a given file is, Broot will be very helpful in that scenario because it can scan the entire file system and show the location of the file to you.
- File managers
  - Thunar (works very well. no other file managers are really necessary if we have this.)
  - PCManFM (not really necessary if you already have Thunar)
  - Vifm is a curser based vi[m] like file manager extended with some useful ideas from mutt. If you use vi[m], vifm gives you complete keyboard control over your files without having to learn a new set of commands. It goes not just about vi[m] like keybindings, but also about modes, options, registers, commands and other things you might already like in vi[m].
- System Monitors
  - HTop  
- Screenshot utility
  - Flameshot (never used)
- Office suites
  - Libre office (This works for most of the scenarios. If we have this, no other office suite is necessary.)
  - Open office (never used)
  - Calligra (never used)
  - wps office? (used - the interface is good. But support for fonts is not as good as that of LibreOffice? Some fonts were totally unreadable)
- img2pdf (to convert images into pdf documents) - (usage: in terminal: $ img2pdf img1.png img2.jpg -o out.pdf) (img2pdf --help)
- pdf arranger (to work with pdf documents - joining multiple pdf documents into one)
- GNU web browser - to keep firefox and regular surfing separate (Chromium is an alternative to this).
- Variety (Nitrogen is an alternative) - wallpaper utility tool. Generally, there are great wallpapers on unsplash.com. There is an option in Variety's preferences to pull wallpapers from unsplash.
- USB Stick Formatter
- USB Image Writer
- Xfce4-screenshooter

-----------------------------------------------------------------------------------------

*** Wizdler

Parses the WSDL files and generates SOAP messages for you # Wizdler

Recognizes WSDL information on the page to show you the available services and operations. Click the operation to generate the SOAP requests and view the response. By clicking the service, you can download WSDL and external XSD files in single ZIP file.

-----------------------------------------------------------------------------------------

*** Hosts file

   Access your hosts file on your services slice (C:\Windows\System32\drivers\etc)
 
-----------------------------------------------------------------------------------------

*** Issues encountered while working with MongoDB

Issues encountered while working on Employee Lambdas using MongoDB : 

mongodb is refusing connections:
go to AWS security group and open up port 27107 (port range 0 - 65535)

-----------------------------------------------------------------------------------------

A website that displays the information that the browser can collect from the computer:
This shows what info the browser can send to other parties with/without our consent.

https://www.deviceinfo.me/

-----------------------------------------------------------------------------------------
