*** Killing a process

    **In Windows machines**
If you need to kill a process manually on Windows it’s actually pretty easy. First, fire up a command prompt and type the following command.
    #+BEGIN_EXAMPLE
    netstat -a -o -n
    #+END_EXAMPLE

To kill the process we need to find the PID of the process in question. I just run down the list by port until I find port 8080 and here you will see the process id was 28344.

Finally, with the PID we can run the following command to kill the process

    #+BEGIN_EXAMPLE
    taskkill /F /PID 28344
    #+END_EXAMPLE


    **In Linux**

This command will print you PID of process bound on that port :
    #+BEGIN_EXAMPLE
    fuser 8080/tcp
    #+END_EXAMPLE

And this command will kill that process : 
    #+BEGIN_EXAMPLE
    fuser -k 8080/tcp
    #+END_EXAMPLE

    **Issue with port 80 being blocked**

If anyone is running into issues with port 80 blocked while setting up their new slice, I have a workaround if you would like to use it. I have an open ticket with VDE support to see about getting the Citrix Virtual Desktop Service changed to a different port.  I will let you know when they have verified this fix or have a different workaround.
I have been able to successfully reboot my slice several times and log back into the Citrix Workspace with no issue.
Verify it is the Citrix Desktop Service running over port 80 by using the following command (as Admin):
    #+BEGIN_EXAMPLE
    netsh http show servicestate | findstr HTTP
    #+END_EXAMPLE
Run the following command to change its port (you should run netstat -aon to make sure the number you choose is free).
    #+BEGIN_EXAMPLE
    C:\Program Files\Citrix\Virtual Desktop Agent\Agent Configuration\Agentconfig.exe /portnumber:4150
    #+END_EXAMPLE
Restart the Citrix Service (or reboot your machine)
