* My Emacs notes
  
  
** Helpful tips related to configuration and other things related to Emacs that I find useful.

*** How to view the list of all the currently installed packages in Emacs?

If you are using Emacs in one machine, and if you want to set-up the exact same set-up settings in another machine, you need to view the list of installed packages from the package manager.

To see a list of the available packages : M-x list-packages

Run this command till you find the first row of installed package: "C-s installed"

Start selecting with C-SPC.

Go down till you reach built-in packages. Copy with M-w. C-x b for new buffer. Paste with C-y.C-x C-s to save file.

Another alternative is, simply copy the ".emacs" file from this computer to the other computer.

------------

*** How to add MELPA as another source of packages in addition to GNU's elpa?
    1. Hint: In order to avoid having to do this multiple times when switching between multiple machines, save the `.emacs` settings in GitHub so that you can just move it from machine to machine.
    2. The alternative is: In a browser, visit MELPA website and grab the URL for the package archive "https://melpa.org/packages/"
       M-x customize-group -> package -> Go to "package archives" -> "INS" to insert a new entry. Provide archive name and archive URL. Set the "State" to "Save for future sessions".

After making changes to the config to add MELPA as a source of packages, run the following two commands:

  1. M-x package-refresh-contents (to refresh the list of packages)
  2. M-x package-install RET evil (to install the evil package)

To change to mode from some other mode : M-x evil-mode

------------

*** How to work with org-mode and evil-mode?
    It looks like Vim key bindings will work in Org mode as well.

------------

*** Helpful commands
    | Command                    | Description                                                                                                                                                             |
    |----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | C-x b and C-x C-b          | Switching between buffers                                                                                                                                               |
    | C-g                        | Cancelling half-entered commands                                                                                                                                        |
    | C-h m, C-h k, C-h f, C-h a | Getting help on editing modes,keybindings and commands. (just remember C-h and read the prompt in the minibuffer)                                                       |
    | C-x C-c                    | Quitting Emacs                                                                                                                                                          |
    | C-h i                      | The info directory                                                                                                                                                      |
    | C-x k                      | kill buffer                                                                                                                                                             |
    | M-x                        | Invoking commands by name                                                                                                                                               |
    | M-x customize              | to enter customization menu                                                                                                                                             |
    | C-x C-f                    | Visiting (opening) files. (This puts us in Emac's dired mode - directory editor). To create a new file, just start typing the name of the file that you want to create. |
    | C-x C-s                    | Saving files                                                                                                                                                            |
    | g                          | Refresh the listing in dired mode                                                                                                                                       |
    |                            | Refresh the listing in dired mode                                                                                                                                       |
    | C-x b *untitled*           | will open new buffer if not exist                                                                                                                                       |

------------

*** .emacs file

If anything goes wrong with the customizations, delete the ".emacs" file in the home directory and start from scratch again.

------------

Where can I find my .emacs file for Emacs running on Windows?

 

If you want to look at the contents of the file:

Within Emacs, ~ at the beginning of a file name is expanded to your HOME directory, so you can always find your .emacs file with C-x C-f ~/.emacs.

 

If you are trying to find out where the file is as opposed to looking at the contents of the file:

It should be stored in the variable user-init-file. Use C-H v user-init-file RET to check. You can also open it directly by using M-x eval-expression RET (find-file user-init-file) RET

------------

*** Resources for emacs

| How to learn Emacs :: About this guide to Emacs - https://david.rothlis.net/emacs/howtolearn.html                    |
| MELPA - http://melpa.org/#/                                                                                          |
| mastering-emacs-in-one-year - https://github.com/redguardtoo/mastering-emacs-in-one-year-guide                       |
| From Vim to Emacs in Fourteen Days - https://blog.aaronbieber.com/2015/05/24/from-vim-to-emacs-in-fourteen-days.html |
| Howardism - http://howardism.org/                                                                                    |
| Magit User Manual - https://magit.vc/manual/magit/                                                                   |
| The Org Manual - https://orgmode.org/manual/index.html                                                               |
| Org mode beginning at the basics - https://orgmode.org/worg/org-tutorials/org4beginners.html                         |
| EmacsWiki - https://www.emacswiki.org/emacs/SiteMap                                                                  |
| Xah Emacs Site - http://ergoemacs.org/index.html                                                                     |
| https://jaderholm.com/screencasts.html                                                                               |
| https://cestlaz.github.io/stories/emacs/                                                                             |

------------

*** How to auto save an org document in markdown format?
    Install the package 'auto-org-md' and after editing the file in org-mode, switch to it using this : "M-x auto-org-md-mode" to toggle the auto save to markdown functionality on and off.

------------

*** Line numbers

    How to show line numbers in files in emacs?

    emacs has 2 line numbers mode.
    
    Alt+x linum-mode ? old, hack, slow. Emacs 23 (released in 2009).
    
    Alt+x global-display-line-numbers-mode ? Emacs 26 (released in 2018-05)
     
------------
