*** Issues with refreshing dependencies in Eclipse

If there is trouble refreshing the dependencies in Eclipse after making changes to the build.gradle file, follow the steps below:

1. check if you have included eclipse gradle plugin. `apply plugin : 'eclipse'`
1. Go to your project terminal
1. Run `gradle tasks --all` to see the list of all available gradle tasks.
1. If the task `cleanEclipse` is available, run it.
1. If not, run `gradle cleanEclipseProject` and `gradle cleanEclipseClasspath` separately.
1. After that, run `gradle eclipse`
1. Go to the project in eclipse and refresh the project.

This should bring all the latest dependencies down and you should see them in the `Referenced Libraries` section.

*** Gradle commands

Go to the EAR folder in command prompt:

    #+BEGIN_EXAMPLE
    C:\XXXXXXXXXXXXXEAR
    #+END_EXAMPLE
And use this command to build EAR.

    #+BEGIN_EXAMPLE
    gradle clean ear --info
    gradle clean testall --info
    gradle clean testAll ear –-info
    #+END_EXAMPLE

From folder :      C:\XXXXXXXXXXEAR\build\distributions
To folder :        C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins
Windows command to copy the EAR from a source folder to a destination folder:
    #+BEGIN_EXAMPLE
    xcopy C:\XXXXXXXXXXXXXXEAR\build\distributions C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins
    #+END_EXAMPLE

From folder :      C:\Users\n0281526\Documents\services-property-insurance-partner-exchange\PiAcordSalesMediationServiceEAR
To folder :        C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins
Windows command to copy the EAR from a source folder to a destination folder:
    #+BEGIN_EXAMPLE
    xcopy C:\WASLP_dev\workspaces\git_repo\services-property-insurance-partner-exchange\PiAcordSalesMediationServiceEAR\build\distributions C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins
    #+END_EXAMPLE


To exclude a few tasks from the build process : 
    #+BEGIN_EXAMPLE
    ./gradlew build -x checkstyleMain -x findbugsMain -x test -x jacocoTestCoverageVerification -x pmdMain
    #+END_EXAMPLE
