
| Websites to help improve typing skills                                                                                |
|-----------------------------------------------------------------------------------------------------------------------|
| typing.com                                                                                                            |
| typingclub.com                                                                                                        |
| key.br                                                                                                                |
| 10fastfingers.com                                                                                                     |
| keyhero.com                                                                                                           |
| typings.com                                                                                                           |
| typeracer.com                                                                                                         |
| zty.pe (like a shooting game. fun to play)                                                                            |
| https://typingtestnow.com/lessons/free_typing_lessons/1.html (There is good information about improving skills here.) |

-------------------------------------

*** Typing Lessons 1: Introduction to the Home Row

Have you already tried to take an online typing test, only to be disappointed with the score you got on that typing test? One problem for many people who are just starting to learn touch typing is that they don't know where to place their hands on the keyboard. That's why each of these typing lessons will start with a review of the correct hand position before moving on to show you which fingers are used for each key.

Here's a basic rule of touch typing: never look down at the keyboard. Your fingers need to learn to move to the right keys without your eyes directing them. In your typing practice, you need to keep your hands over the home row so that your fingers are always moving in the same way to reach the same keys. The home row is the middle set of letter keys on the keyboard. Every time one of your fingers move away from one of the eight home base keys in the home row to strike another letter key, it needs to come back to the same home base key immediately afterwards.

When you're just starting to learn touch typing, don't worry about speed. You won't be ready to take a typing speed test until you've learned how to keep your hand positioned over the home row, and only move your fingers to the other keys. In this lesson, you'll learn which of the home row keys are your home base keys, and how to practice moving your fingers without moving your hands.

Most people who are keyboarding online are using a laptop or computer keyboard. These typing lessons will teach you how to use the standard QWERTY keyboard, and how to use all of your fingers and thumbs to touch type. Remember, you won't do well on a typing test if you're "texting" the letters with only one or two fingers!

To start this lesson, let's look at the home row and its eight home base keys:

A         The tip of the pinky (little finger) on your left hand should rest on top of this key.
S          Keep the tip of your left-hand ring finger on this key.
D         Rest the tip of the middle finger on your left hand on this key.
F          Place the tip of the index finger of your left hand lightly on this key.

J           The tip of your right-hand index finger belongs on this key.
K         Put the tip of the middle finger on your right hand on top of this key.
L          Keep the tip your right-hand ring finger lightly on this key.
;           Place the tip of the pinky on your right hand on this key.

Are all of your fingers in place? You'll probably feel a small bump under your two index fingers on the F and J keys. These bumps will help you keep your hands in the right place as you start keyboarding online.

Your thumbs should rest lightly on the space bar. You can press the space bar with either thumb. Some people use their two thumbs alternately, while others tend to use the thumb on their dominant hand to press the space bar. If you're right-handed, you may find it more natural to use your right thumb. To find out which feels more comfortable, find a free typing test online and go through it without worrying about your accuracy - just focus on using the space bar. With a little practice this movement will become habit.

Before you move on to the next lesson or to take a typing test, practice moving your fingers away from and then back to the home row and home base keys.

-------------------------------------

*** Typing Lessons 2: The Right-Hand Home Row Keys

A good typing practice session will give you a chance to use all of the keys on the keyboard, including letters, numbers, and symbols. When you're first starting to learn touch typing, it's best to start out learning keys and keystrokes in smaller groups. That's why you should only take a typing test at this point if it focuses on a few letters rather than the entire keyboard. If you try to take a test using all of the keys, you may get discouraged, because your score on an average typing speed test will be fairly low. But if you go through all of these typing lessons in order, you will learn each group of keys before moving on to the next one, and you'll find that keyboarding online will be much easier.

If you were wondering in the last lesson why we skipped over the H key on the keyboard, it's because the H key is not one of the home base keys. Remember, the home base keys for your right hand are the J, K, L, and ; keys. Rest both your hands on the home row with your fingers in the correct position, and go through the typing test below to see if you can press the correct keys with the right fingers every time. Ready?

J K L ;

J L K ;

K J L ;

L K ; J

; L K J

; K J L

Did you make any mistakes? Go through these keystroke combinations until you are confident that you can accurately hit each key at the right time, with the right finger. Remember to keep your hand in the same position over the home row.

To press the H key, move your index finger from the J key to the left. Press the H key, and then move your index finger back into position on the J key. Practice that movement a few times until it feels comfortable, and then go through the typing test below:

H J K L ;

J H L K ;

K J H L ;

L K ; H J

; L K J H

H ; K J L

Now that you've practiced with all five of the right-hand home row keys, go back to the online typing test you used to practice with the space bar, and take it again. Focus on these five keys (plus the space bar) and don't worry about the other keys and letters right now. You might want to bookmark any free typing test you find that helps you practice like this, because it's a good way to do quick practice sessions when you have a few minutes. The more you practice, the easier these finger movements will become.

-------------------------------------

*** Typing Lessons 3: The Left-Hand Home Row Keys

As we discussed in the last lesson, it's important that you learn to keep your hands in position over the home row when you're keyboarding online. If you notice that you're moving your entire hand as you go through these typing lessons, try resting your wrist on the edge of the laptop, or the wrist rest built into most plug-in keyboards. Some of the newer, smaller keyboards don't have these wrist rests, so keep the base of your palm or your wrist in contact with the table or desk as you work on your typing practice. Don't put too much weight down on your wrists as you're touch typing, though. This can lead to problems with the tendons and muscles in your wrists, hands, and arms. Just use enough pressure that you're not as tempted to move your hands as you type. If you're not sure whether or not you're moving your hands too much, get a friend to watch your hands as you go through a typing test. Remember, you're not supposed to be looking down at the keyboard, so you can't watch your own hands!

If you went through an online typing test to practice using the space bar and the right-hand home row keys, and you had your hands in the correct position on the home row, you probably found yourself automatically pressing the left-hand home row keys during that typing test. That's good! It means that your fingers are starting to learn the right movements to make and the right keys to hit, even if you're not thinking about those keys. In this lesson, we'll focus on those left-hand home row keys.

We'll start out with a review of the four home base keys you strike with your left hand. When you're practicing the keystrokes to reach the letters shown below, don't treat it as a typing speed test. What's important right now is accuracy, not speed. Once your fingers know exactly where to go, you'll be able to concentrate on improving your speed. However, if you don't focus on accurate finger placement now, you run the risk of developing bad typing habits. By avoiding bad typing habits now, you'll find it easier to take even the most difficult typing test in the future, because you'll make many fewer mistakes.

Practice these letter sequences using your left hand. Remember to keep both hands in the correct position at the home row, even if you're not using your right hand to type at this point.

A S D F

F S D A

S D A F

F S A D

S F A D

D S F A

Now add the letter G. To reach the G key, move your left-hand index finger to the right. Don't forget to move it back to the home row position over the F after you have pressed the G key.

A S D F G

G F S D A

S G D A F

F S G A D

S F A G D

D S F A G

Are you able to follow these keystrokes without making a mistake? Don't worry about speed at this point, just make sure you are hitting the right keys with the right fingers, and keeping your hands in position over the home row keys. After you've practiced with the letter sequences above, go back to the free typing test you bookmarked and try it again. As before, just concentrate on these left-hand keys, but don't stop your right hand from hitting the correct keys if it wants to!


-------------------------------------

*** Typing Lessons 4: Using the Shift and Enter Keys

Some online typing tests only use lowercase letters, and that's fine when you're just starting out to learn where all of the keys are on the keyboard. However, when you're typing in the real world, you need to use both uppercase and lowercase letters. Take a look at the keyboard - yes, you can look down at the keyboard right now, but not while you're touch typing! You'll notice that while each of the letter keys has just a single letter, all of the other keys that have numbers or symbols have two characters per key instead of one. In order to use the uppermost character on a key, or to make capital letters, you need to learn how to use the Shift key.

If you've done any typing practice at all, you'll know that there are actually two Shift keys on the standard QWERTY keyboard, one on the left and one on the right, at each side of the bottom row on the keyboard. Which one you use depends on the letter or character you need to type. In general, you will press the Shift key with the pinky finger of the hand that is NOT going to be used to press the letter or character key you want to type.

Does that sound confusing? Most typing lessons try to explain this in several different ways, but it's really very simple. We'll use the two of the letters of the home row as an example:

The J key is typed with the index finger of your right hand. To make a capital letter J, press the Shift key with the pinky of your left hand and hold it down while you press the J key with your right hand.

The D key is typed with the middle finger of your left hand. To make a capital letter D, press the Shift key with the pinky of your right hand and hold it down while you press the D key with your left hand.

That's easy enough, isn't it? If you're going to press the letter or symbol key with the right hand, you'll press and hold the Shift key with the pinky of your left hand. If you're going to press the letter or symbol key with the left hand, use the pinky of your right hand to press and hold the Shift key. While this might not make sense right now, once you take your first typing speed test you'll quickly realize that using this balanced approach helps you type even faster. If you don't think that's true, look up any free typing test on line and try taking the typing test several times. Practice with the balanced alternating hand technique described above, and then try it again using the left and right Shift keys randomly. You will find that it is hard to press and hold the Shift key with one hand and also press a letter or symbol key with another finger on that hand. If you don't want to have slowed-down typing test results, make sure you use the alternating hand technique you learned in this lesson.

Another important key is the Enter key. On a standard QWERTY keyboard, the Enter key is at the far right side of the home row. Whether you are right-handed or left-handed, you'll need to practice using the pinky finger on your right hand to hit this key. Some people who are used to keyboarding online in text messages or casual e-mails might not use the Enter key as often, but any typing test you take will require you to separate paragraphs, sentences, or even words in order to get a good score.

-------------------------------------

*** Typing Lessons 5: Apostrophes and Quotation Marks

If you're continuing your typing practice after Lesson 4 and going straight into Lesson 5, you might want to take a break for a few minutes first. That's because we're going to be talking about another key and set of characters that requires you to use your right-hand pinky finger. Don't worry - this is the last of these typing lessons where one finger will have so much to do! In this lesson, we're going to look at apostrophes and quotation marks. Both of these symbols are found on the key to the right of the home row on a standard QWERTY keyboard, between the ; key and the Enter key.

You'll probably find that you use apostrophes much more often while touch typing, but it's important to learn to use quotation marks as well. For one thing, when you're taking a typing test, you'll almost always be tested on this symbol. Apostrophes are more common in everyday keyboarding online, because they're used in words that are possessive or are contractions. Here are some examples of words and phrases that use an apostrophe:

she won't go to school
the cat's outside the door
his brother's older than he is
my mother's car is blue

Previous typing lessons covered the letters of the home row, and explained how to use the Shift key to create capital letters or switch between the two characters on the ; key. Take this quick typing test to go through some home row key combinations:

A Lad Has A Sad

JAG; HAD; LASH; GAL

Hall: Alas: Flag

Did you remember to use the opposite pinky finger to press and hold the Shift key?

To type an apostrophe or a quotation mark, you need to move the pinky finger on your right hand to the right, but not as far as you need to reach to hit the Enter key. At first, you might accidentally hit one instead of the other, but don't worry - you're not taking a typing speed test, so relax and concentrate on pressing the right keys, not how fast you're typing. Take as long as you need to get comfortable with this movement. If it helps, go back to the free typing test you bookmarked and practice with that, focusing only on the apostrophe key when it appears in the typing test.

Once you're comfortable with pressing the apostrophe key with your right-hand pinky finger, add the Shift key to create a quotation mark. Remember, you press the Shift key with your left-hand pinky finger and hold it down while you press the apostrophe key with your right-hand pinky finger. Repeat this keystroke sequence until you have both movements under control:

'   '   '   "   "   "   '   '   '   "   "   "   '   "   '   "   '   "   '   "   '   "

Now try typing these letter combinations using all of the keys on the home row:

Jad: "had gal's salad"

"Hall; Flag"

Fall's had a GLAD gala

Congratulations! You know all of the keys on the home row now. This is a good time to go back to any online typing test you took before you started these touch typing lessons. Take the typing test again, and see how much you've improved already!

-------------------------------------

*** Typing Lessons 6: The Left-Hand Top Row Keys

It's time to move away from the home row keys and look at some of the other letters and symbols on the standard QWERTY keyboard. But remember - when we say "move away" we don't mean moving your hands away from their position on the home row! As you learned in the first of these typing lessons, always keep your hands in the same place, with the tips of your left-hand fingers resting lightly on the A S D and F keys, and the tips of your right-hand fingers on the J K L and ; keys. Keep your wrists flat and just touching the desk or edge of the keyboard. It's important to be in the right position when taking a typing test or when touch typing in general, otherwise your speed and accuracy will go down. What's more, if you spend a lot of time keyboarding online, poor hand position may lead to problems with your muscles, all the way up to the muscles in your neck and back. If you're regularly taking an online typing test, you're already going to be under pressure to perform, especially if it's a typing speed test. Keep your wrists and arms relaxed as you go through any typing practice sessions.

The left-hand top row keys should be familiar by now, because we've mentioned them several times already. They're the keys that gave the keyboard you're using its name: QWERTY (the Y is actually typed with one of the fingers of the right hand, and we'll cover that in the next lesson).

Here are the finger movements you need to learn in order to type these letters:

To type the Q, take your left-hand pinky finger off the A key and move it up to the top row.

Type the W with the ring finger of your left hand, then move the finger back to the S key.

Use the middle finger of your left hand from the D up to the E key, then back again.

Type the R using your left-hand index finger, returning to the F key afterwards.

Move the index finger of your left hand up from the F key and to the right to the T key.

Practice these keystroke movements with the short typing test below. You can use the Shift key to create capital letters, or simply type lowercase letters. Repeat this typing test until you're comfortable with the finger movements and are not making any mistakes.

F T F R F T F

D E D E D E

S W S W S W

A Q A Q A Q

A S D F Q W E R T

F T F R D E S W A Q

F D T R A S Q W

D E R S F Q A T W

If you have found a free typing test that lets you choose which letter to focus on, try taking that test until you're completely familiar with the left-hand keys on the home row and top row. Try to include a mix of capital and lower-case letters so that you practice pressing the Shift key with your right-hand pinky finger as you strike the letter keys with your left hand.

-------------------------------------

*** Typing Lessons 7: The Right-Hand Top Row Keys

If you're getting bored with typing lessons because you have to type random letter combinations, don't give up. The more letters you learn, the more real words you'll be able to type, and the better you'll do on any typing test. The secret to professional touch typing is knowing each keystroke finger movement so well that you don't have to think about it. That means that you're going to have to put in a lot of typing practice!

In this lesson, we'll look at the top row keys that you hit with the fingers of your right hand. After you learn which keys are pressed by each finger, you'll have another typing test to take.

Move the index finger of your right hand up and to the left to press the Y key.

Use the same finger to press the U key on the top row, then return it to the J key.

Move the middle finger of your right hand from the K key up to the I key and back again.

To type the letter O, stretch your right-hand ring finger from the L key up to the top row.

Press the P key with the pinky finger on your right hand, then place it back on the ; key.

Now try these letter and symbol sequences. It's not a typing speed test, but an accuracy test, so only try to build up speed gradually. Use the Shift key if you want to practice switching between uppercase and lowercase letters. Remember to press the Shift key on the left with your left-hand pinky finger while you're learning these right-hand top row keys.

J Y J U J Y J U J Y J U

K I K I K I K I

L O L O L O L O

; P ; P ; P ; P ; P ;

L O L ; ; ; J U J

I U K J I L ; O P

P O P K ; I J U Y

Here's another free typing test so that you can practice using the keys on the home row and the top row to create real words and phrases. When you're typing a word, try to think of it as a whole word and not as a series of letters. This will help your brain to signal your fingers to type all the letters in sequence, rather than sending those signals for individual letters.

wet   rest   saw   quirk   play   kids   treat   usual

Jack   Jill   Gail   Larry   Papa   Mom   Lois   Hugh

"this is typed with these keys"

he's set

she is really healthy

Help to type well: type "test help"

You know enough about most of the common keys now to get some good touch typing practice just by doing your daily keyboarding online. Whether you're typing e-mails to friends or writing a paper for a school assignment, taking an online typing test or just surfing the internet, practice the correct hand position so that it becomes a habit. It's a good idea to take another typing test at this point so that you can have more fun typing real words and phrases. Stay motivated, keep learning, and get ready to learn more letters and symbols in the next lesson!

-------------------------------------

*** Typing Lessons 8: The Left-Hand Bottom Row Keys

The last row of letters and symbols on a standard QWERTY keyboard is on the bottom row. This row is sometimes hard to learn, but regular typing practice will help you train your fingers to make the movements down to these keys. You've probably noticed when you've been taking a typing speed test that you slow down a little bit when you are searching for the bottom-row keys. That's because moving your fingers down and back is not a natural movement for most people. We tend to find it easier to move our fingers out and forward, not down and backward. But that's what these typing lessons are all about: teaching you the easiest and best ways to learn touch typing.

The letters and symbols on the bottom row include a few letters that you probably won't use as often, and two symbols that you'll be using all of the time when you're keyboarding online. After we look at the keys and the fingers you use to press them, you'll take a typing test to practice how these finger movements feel.

The keys on the left-hand side of the bottom row of a standard QWERTY keyboard are as follows:

Z   X   C   V   B

When you're typing in English, the Z, X, and V keys won't come up very often, but you need to practice them as well, otherwise you won't be able to score well on any standard typing test.

Place your hands in position on the home row, with your eight fingers over the home base keys, and then practice the left-hand finger movements explained below.

To press the Z key, move your left-hand pinky finger down from the A key and back again.

Strike the X with the ring finger of your left hand, then place it back on the S key.

The C key is pressed with the middle finger of your left hand, which returns to the D key.

Move the index finger of your left hand down to the V key, then back to the F key.

Use the same finger to move down and to the right to hit the B key.

Go through these instructions and practice the finger movements until you feel comfortable with them. You can go to the online typing test you bookmarked and practice with that, but only focus on the keys on the left side of the bottom row when you're worrying about accuracy. Remember to keep your hands in the correct position on the home row at all times, and only move your fingers.

Now that you've had a chance to practice with the bottom row keys, take this free typing test to see how quickly and accurately you can strike the correct keys in sequence. You can use the Shift key to create capital letters if you like.

A   Z   S   X   D   C   F   V   F   B

B   V   C   X   Z

A   B   S   V   D   C   F   X   Z

Z   A   B   F   X   S 

C   D   C   F   Z   V   A   F   B

S   D   X   C   A   F   Z   V   A   B

Don't worry if these finger movements still feel a little awkward. Each time you take a typing test, they will become more natural, and your accuracy and speed will improve.

Here's one more typing test to help you get used to using the Shift key when you type. This free typing test uses all of the letters on the top row, the letters and symbols on the home row that you learned in the first seven typing lessons, and the five letter keys you just learned.

Quite good cake; really very lush taste

"Zebras have stripes"

He's just a little "weird"

You will keep quiet

"Expert Typist Here"

Five boys just bought: apple pie

-------------------------------------

*** Typing Lessons 9: The Right-Hand Bottom Row Keys

This is the last of the typing lessons to teach you where to find the letters of the alphabet on the keyboard. The keys on the right-hand side of the bottom row of a standard QWERTY keyboard are as follows:

N   M   ,   .   /

You'll definitely be using the comma (,) and period (.) keys regularly when you're keyboarding online, so take all of the time you need to get familiar with these last five keys and the letters and symbols on them. The second symbol on the / key is the question mark (?) and you'll get a chance to practice that symbol in a typing test, after you learn the correct finger movements.

Place your hands in position with your fingers over the home base keys, then go through the right-hand finger movements as follows:

Press the N key with the index finger on your right hand, then return it to the J key.

Your right-hand index finger also presses the M key downward and to the right.

Move your right-hand middle finger from the K key to the , key and back again.

Take your right-hand ring finger off the L key, move it down to the . key then back.

Use the pinky finger on your right hand to move down to the / key and back to the ; key.

If you're normally left-handed, you might have problems at first using your right-hand pinky to reach the key on the bottom row. However, you need to practice getting more strength and accuracy with your right-hand pinky finger. As you'll remember from previous typing lessons, that's the finger you use to press the Enter key, and also the Shift key for left-hand keystrokes. But don't worry - even right-handed people need typing practice to get used to these keystroke movements!

Practice the following key sequences using these new letters and symbols. You can use the Shift key to create capital letters if you like, but don't use the Shift key on the symbol keys yet.

N   M   ,   .   /

/   .   ,   M   N

N   J   M   K   ,   L   .   ;   /

/   ;   .   L   ,   K   M   J   N

J   /   N   ;   .   K

L   M   J   ,   K   /  .  N   ;

Don't worry if these finger movements still feel a little awkward. Each time you practice touch typing, they will become more natural, and your accuracy and speed will improve.

This is a good time to take an online typing test, because you've learned the finger movements for all of the keys on the three main keyboard rows. Focus on the getting all of the right-hand bottom row keys correct during that typing test. Don't take a typing speed test yet, though. You still need to concentrate on keeping your hands in the correct position, and only moving your fingers while you strike the keys.

Here's one more typing test to help you get used to using the Shift key. Now that you can use all of the letters and symbols on the top, home, and bottom row, there's no limit to the words and phrases you can type!

"Help," she said; I answered.

Are you going to eat that cake?

Let's go to the zoo today.

Quick: take this free typing test now.

Do you expect to receive an excellent score next week, James?

This is the division sign: /

-------------------------------------

*** Typing Lessons 10: The Left-Hand Number Keys

In the first nine typing lessons of this series, you learned where all of the letters of the alphabet are found on a standard QWERTY keyboard. You also learned which fingers to use to strike each of those keys, and the importance of returning each finger to its home row position to help you be as accurate as possible when touch typing. You got typing practice with some of the common symbols that you'll use every day when keyboarding online, like the comma (,) and colon (:) and question mark (?). We gave you several free typing tests to help you learn how to use the Shift keys correctly; do you remember that rule? If you said "always press the Shift key with the pinky finger of the hand opposite the one used to strike the letter or symbol key" then congratulations! You've got all the basics down, and you should already be noticing an improvement in your score when you take a typing speed test.

In these next typing lessons, we'll introduce you to the number keys. While it's true that many computer keyboards have numeric keypads that people often use to type numbers, these lessons will show you how to use the regular QWERTY keyboard keys to type them. There are several reasons for this: first, if you're using a laptop like many people do, there probably isn't a numeric keypad - you'd have to switch some of the letters over to numbers, and then remember to switch them back. That will definitely slow you down when you're taking a typing test! Second, a numeric keypad is most useful when you're doing data entry. If you're looking for an office job, you may be asked to take an online typing test for numeric data entry, so it's a good idea to practice with a keypad for that purpose. However, when you're touch typing on a daily basis, you'll find it easier to use the number keys at the top of the QWERY keyboard.

This lesson covers the numbers you'll type with your left hand. After you learn the finger positions, you'll take a short typing test to practice moving your fingers to and from the home base keys on the home row.

Move your left-hand pinky finger from the A key to the 1 key on the top row.

Type the number 2 with your left-hand ring finger, then return that finger to the S key.

Use the middle finger of your left hand to type the number 3 then place it back on the D key.

Move your left-hand index finger from the F key up to the number 4 and back again.

Use the same index finger to press the 5 key, then return your index finger to the F key.

Now type the following letter and number sequences to practice those finger movements:

F 5 F 4 F 4 F 5

D 3 D 3 F 4 D 3

S 2 S 2 D 3 F 4 F 5

A 1 A 1 S 2 S 2 D 3 F 4 F 5

3 F 4 S 5 A 1 S 2

1 5 2 4 3 D 3 F 1

Here's another typing test that will help you practice these five number keys. The following sentences use all of the letters and symbols you've learned so far, including the numbers 1 through 5. The more time you spend in typing practice, the more natural the finger movements will be, so take a few minute every day to type these sentences, or ones like them. Remember to use the Enter key to separate the sentences, and to use the Shift key correctly when typing.

A queen doesn't need to ask permission before sitting down to 11 o'clock tea, does she?

I don't remember whether the answer is in Chapter 3 or Chapter 4, but you need to learn the exact rules governing good grammar or you'll score less than 25 points on the exam. That grade would put you in the "almost failing" category.

Keep calm: carry on.

45 / 3 is equal to 15.

Julian is very tall; Camille is rather short.

Don't mix up the number 2 with the words "too" or "to."

-------------------------------------

*** Typing Lessons 11: The Right-Hand Number Keys

Your touch typing should feel more natural now that you've had the chance to get some typing practice with each free typing test that uses all of the letters on the standard QWERTY keyboard. If you're still having problems or feel like you need to look down at the keyboard as you type, try going back to earlier typing lessons and reviewing specific keystroke movements. Another good way to practice is to spend as much time as possible keyboarding online, using practice texts and focusing on accuracy instead of speed. While you can take a typing speed test just to see what your current word per minute (wpm) score is, don't worry about speed right now. In fact, for some people it's a good idea to avoid taking any typing test until they get more familiar with all of the keystrokes and finger movements. That's because it can be discouraging to get a low score on an online typing test. Remember that practice makes perfect, and right now you should be concentrating on getting as much practice time on the keyboard as you possibly can. Keep your hands in position on the home row, keep your eyes on the screen instead of the keyboard, and if you want to take a typing test, try for a high accuracy score rather than a high speed score.

In this lesson, you'll learn the other five number keys on the top row of the keyboard. As we said in the last lesson, it's a good idea to learn how to type numbers on the standard QWERTY layout rather than using a numeric keypad. If you want to learn how to do numeric data entry or calculations using a keypad, that's something you can do later, after you have all of the basic touch typing principles learned. However, you'll probably find it a lot more efficient to type numbers using the keyboard keys instead of the numeric keypad keys when you're keyboarding online on a day-to-day basis.

Here are the finger movements for the numbers 6 through 0 on the QWERTY keyboard:

Move your right-hand index finger from the J key to the 6 key and back into position.

Use the right-hand index finger again, reach up to the 7 key, then move it back to the J key.

Stretch the middle finger of your right hand up from the K to the 8 and back again.

Move the ring finger of your right hand up to the 9 key and back into position on the L key.

Use your right-hand pinky finger to press the 0 key, then put it back on the ; key.

Go through these finger movements until you're confident that you can press all five number keys accurately, while always returning your fingers to their proper position on the four home base keys of the home row.

Are you ready for another typing test? These two paragraphs having you using all of the numbers, all of the letters, and all of the symbols you've learned so far. Remember: accuracy, not speed!

Do you know the song "Inchworm" that Danny Kaye made famous in 1952? It's in the film called "Hans Christian Andersen." Most people remember it for one reason: the chorus. Here's how it goes: "2 and 2 are 4; 4 and 4 are 8; 8 and 8 are 16; 16 and 16 are 32." That film came out a very long time ago, so maybe only 1/3 of people today know the song. When I asked my friends, 0 people had heard of the film, but 7 of them could sing the song quite well.

Just 5 more lessons, and you'll have mastered the exact sequence of finger movements to correctly type all 60 standard letters, numbers, and symbols on a standard QWERTY keyboard. You're on your way to becoming a true typing whiz kid. 

-------------------------------------

*** Typing Lessons 12: Parentheses and Other Brackets

The things you'll need to type when you're keyboarding online will depend on what you're doing. Do you think you'll just be on social media sites, chatting with friends, or commenting on blog posts? You'll probably only use the letter and number keys, and some of the common symbols when you're touch typing if you're a casual user, and you probably won't need to type more than about 40wpm. Any free typing test will help you determine whether you've reached that goal already. While accuracy is still very important, you don't need to be as concerned about speed.

However, if you're a student with papers to write, or if you do most of your communications through longer e-mails, then you should think about speed as well as accuracy. After you're done with this series of typing lessons, take a typing speed test to check your words per minute. Someone who depends on fast, accurate communication should be able to type at least 60wpm with an accuracy of 80% or above. For students or anyone else who needs to write a lot of papers or produce a lot of documents, this is the minimum speed required to make sure you can keep up with your work load.

When you want to make your living as a typist, or if typing is a key function of your job, you should look carefully at the results of you online typing test. In general, someone who needs to spend most of their time at work at the keyboard should be able to type at least 80wpm with an accuracy rate of 95% or better. But don't be discouraged if you're not there yet! Just keep working on your typing practice, take as many typing tests as you can, and review any keystrokes or finger movements that are slowing you down or causing you to make typing errors.

This lesson explains how to type the symbols called "brackets." There are three types of brackets: parentheses ( ), square brackets [ ], and curly brackets { }. You'll probably use the parentheses most often, but you need to know how to type square brackets and curly brackets as well, especially if you have an office job or are studying in the field of math or science. After practicing the finger movements explained below, go through the typing test and get used to the keystroke sequences you need to type these symbols.

The parentheses are found above the 9 and 0 keys. To type the left bracket, press and hold the Shift key with the pinky finger of your left hand, and strike the 9 key with the ring finger of your right hand. To type the right bracket, press and hold the Shift key with the pinky finger of your left hand, and strike the 0 key with the pinky finger of your right hand.

The square brackets are found on the two keys to the left of the top row of letters on a standard QWERTY keyboard. Use your right-hand pinky finger to press these keys to make the left and right brackets. Return your right-hand pinky finger to its position on the ; key afterwards.

The curly brackets are on the same keys as the square brackets. Use the pinky finger of your left hand to press and hold the Shift key, then use your right-hand pinky finger to type the curly brackets. Release both fingers and return your hands to position on the home row.

Now take this typing test to practice using all three types of brackets:

(Here's an example of the curved brackets normally called "parentheses.")

[This sentence is enclosed in square brackets.]

You won't often need to use curly brackets, you'll often see them used to represent sets in mathematics, like this: P = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29 ...}.

-------------------------------------

*** Typing Lessons 13: The Left-Hand Symbol Keys

Now that you've learned all of the letters and numbers, the rest of these typing lessons will help you learn all of the symbols on the standard QWERTY keyboard. You'll use some of these symbols quite often when you're keyboarding online, others only infrequently, and some symbols you may never use - but it's a good idea to learn where they are on the keyboard, just in case. Some online typing tests make a point of testing you on every single key. What's more, it's not unusual for employers to give prospective employees a typing test as part of the hiring process for many office jobs. In order to show that your touch typing is at a professional level, you'll need to know all of the keys.

There are 7 symbols you'll type with the fingers of your left hand. All but one of them require you to also press the Shift key with the pinky finger of your right hand at the same time. Repeat this typing practice sequence as many times as you need.

At the far left of the top row of keys is the single quote ` key. Press this key with the pinky finger of your left hand. You do not need to press the Shift key to type the single quote.

On the same key, you'll find the tilde ~ symbol. Hold down the Shift key with your right-hand pinky and press the ` key with your left-hand pinky to get the ~ symbol above it.

For each of the following symbols, you need to hold down the Shift key with your right-hand pinky finger while pressing the appropriate key with one of the fingers of your left hand.

Use the pinky finger of your left hand to type the exclamation point ! above the 1 key.

Move your left-hand ring finger up to the 2 key to type the @ symbol above it.

Type the # symbol with the middle finger of your left hand using the 3 key.

The dollar sign symbol $ above the 4 is typed with the index finger of your left hand.

Use your left-hand index finger to type the % symbol on the 5 key as well.

Although you may only ever use some of these symbols during a typing test, you do need to practice them. As we mentioned above, most workplace typing speed tests will require you to use all of the symbols on a standard QWERTY keyboard, just to show that you can find those keys without slowing down too much. To help you practice locating and typing these symbols, go through the free typing test below. You'll learn when and where to use the symbols while you practice!

Any time you want to show a percentage, you'll use the % key, as in "20% of 80 is 16."

In the United States, prices are calculated in dollars. You can expect to pay around $3.50 for a gallon of milk, but a pound of bananas is usually $1.00 or less.

When you're finished with this typing test, you'll be #1 at typing all 7 of these symbols!

Anyone who uses a computer knows that the @ symbol is used in e-mail addresses. But did you know that the name for the @ symbol in Czech means "pickled herring"?

The tilde symbol is often used in Spanish, but on the QWERTY keyboard the only common use is before a number or quantity, to mean "approximately." Here's an example: "The value of pi is ~ 3.14."

Depending on the font type you choose, you may need to use the single quote along with the apostrophe to embed a quotation, like this: "She thinks that using symbols `is just silly' but she needs to learn to type them anyway."

-------------------------------------

*** Typing Lessons 14: The Right-Hand Symbol Keys

Your typing practice continues in this lesson, where you'll learn the symbols that are typed with the fingers of the right hand. You've already learned two of these: the parentheses, which we covered in the twelfth of these typing lessons. If you don't remember how to type those symbols, go back to Lesson 12 and run through the free typing test at the end until you can type them easily.

Let's start this lesson with an explanation of each of the right-hand top row symbols. Again, you might never use these except during an online typing test, but you should be familiar with where they are and what they're used for. Even if you don't do much touch typing now, you might have a job in the future that uses these symbols frequently. After learning what each symbol is, you'll have a short typing test to start practicing how to type them.

The ^ symbol is called the carat symbol, and it's right above the 6 key on the top row of a standard QWERTY keyboard. You'll probably only use this symbol if you're typing a mathematical formula, such as 3^2, which is shorthand for "three to the power of two" or "three squared."

The ampersand is the & symbol on the 7 key, and you'll use this to replace the word "and." Up to a few decades ago, this was a common way of saying "and" but these days it's mostly used in names, like "AT&T."

You will use the asterisk * found above the 8 when you're typing a document with footnotes,  and sometimes when you're keyboarding online. One asterisk tells the reader to look for a footnote with more information at the bottom of the page. Two asterisks around a word or phrase shows emphasis in a text or e-mail message, like this: "I can't *believe* he said that!"

The hyphen - is found on the key just to the right of the 0 key on the top row of a QWERTY keyboard. Use hyphens to create compound words like "twenty-one" and "high-stakes."

On the same key, you'll see a longer dash that represents the underscore symbol _. You probably won't use this for its original purpose, because every word processing program now allows you to chose an "underline" mode when typing, so that a series of words is underscored. However, many people use the underscore symbol to create easy-to-read file names, like this: Typing_Lesson_14_results_Nov2015

Now that you know what the symbols are used for, go through this next typing test by following the instructions on how to type them.

Press down the Shift key with your left-hand pinky finger and use the index finger of your right hand to type the ^ and & symbols. Move your finger from the J key to the 6 key to type the ^ symbol, and move your finger from the J key to the 7 key to type the & symbol. Always return your finger to the home row position.

Press down the Shift key with your left-hand pinky finger and move your right-hand middle finger from the K key up to the * key (above the 8) and then back to the home row.

Move your right-hand pinky finger from the ; key up to the - key and back again. Press and hold the Shift key with your left-hand pinky finger and use your right-hand pinky finger to press the same key to type the _ symbol.

There are two more symbols you type with your right hand, the bar symbol | and the backslash symbol \. These are on the same key on a QWERTY keyboard, located to the far right of the top row of letter keys, to the right of the square/curly bracket keys.

Move your right-hand pinky finger from the ; key over to the \ key and back again. Press and hold the Shift key with your left-hand pinky finger and use your right-hand pinky finger to strike the same key, which gives you the | symbol.

At first all of these infrequently-used symbols will probably slow down your total words per minute (wpm) in any typing speed test, but keep practicing and you'll soon be able to hit those keys confidently and accurately. Remember, you'll probably only need to use a few of them regularly, so they won't slow down your overall speed in a standard typing test or when you're keyboarding online.

-------------------------------------

*** Typing Lessons 15: The Delete and Backspace Keys

Why have we waited until the fifteenth of these typing lessons to talk about the Backspace and Delete keys? Because once you're touch typing like a pro, you won't have to use them very often! What's more, it's better to focus on typing smoothly and steadily, rather than worrying about backspacing and deleting mistakes, when you're first learning how to type.

In the typing tests you've done so far, you've probably already used the Delete and Backspace keys, and that's okay. However, many online typing tests - and especially typing speed tests - will disable the Delete and Backspace keys so that you can't go back and fix errors. That's so the test will show a true count of your touch typing accuracy at the end. In general, you'll find that employment-based typing tests will be stricter about this, but that most free typing tests let you go back to correct any typos. Remember, though, each time you go back to fix a mistake, you're slowing down your overall word per minute rate.

Just in case you haven't located the Delete and Backspace keys already, here's where you can find them on most standard QWERTY computer keyboards:

The Backspace key is usually to the right of the top row of number keys. Use your right-hand pinky finger to press this key.

The Delete key is usually found at the very top right of the keyboard. You'll also use the pinky finger on your right hand for this key.

Of course, when you're keyboarding online and writing e-mails, creating text documents, and communicating with people, you need to make sure that what you've typed is error-free before you print out a document or hit the Enter key to send a message. Even if you're able to type at 90wpm, use some of the time you saved typing to check your text carefully. Keep in mind that your computer won't catch all of the errors and typos, because sometimes a mistyped word is still a properly-spelled word, just not the one you meant! Any typing mistake means that you could be confusing the person on the other end of the communication, whether that's via an online e-mail or a printed document. For example, you don't want to send someone a message with directions to meet you for lunch, and tell them to "go tough the crossing" instead of  to"go through the crossing."

The best way to make sure you don't send out messages with errors is to keep up with regular typing practice. Now that you've learned all of the letters and numbers on the keyboard, and almost all of the symbols, go ahead and take a typing test to see where you score on speed and accuracy - but try to avoid the Backspace and Delete keys!

-------------------------------------

*** Typing Lessons 16: Math and Movement Keys

This is the last of the typing lessons in this series where you'll learn how to type new symbols. We'll also introduce you to some useful keys that will help you when you're keyboarding online, with quick ways to get around a block of text or move through a document. Once you're done with this lesson, you'll be able to focus on typing practice that will improve your speed and accuracy. Remember, if you're touch typing and you find that you're frequently making mistakes on one or two keys or symbols, go back through these typing lessons and practice with the appropriate typing test until you're sure you know the right finger movements.

We'll start out with the last of the keyboard symbols found on a standard QWERTY keyboard, the plus sign + and the equals sign =. Unless you're typing out a mathematical formula, you'll probably only use these as shorthand for the words "plus" and "equals." Most people who need to type in a lot of math equations (into a spreadsheet, for example) will use the numeric keypad, but it's a good idea to learn where all of the symbols used in basic math are located on the keyboard.

You've already learned three of these symbols, so let's review those before adding the last two.

To type the multiplication symbol *, press down the Shift key with your left-hand pinky finger and move your right-hand middle finger from the K key up to the * key (above the 8) and then back to the home row.

For the minus symbol - that indicates subtraction, you need to move your right-hand pinky finger from the ; key up to the - key and back again.

Use the pinky finger on your right hand to move down to the / key and back to the ; key to type the division symbol.

Our two new mathematical symbols are located at the end of the number row at the top of the keyboard.

Move your right-hand pinky finger up to the = sign and back to position on the home row ; key. Type the plus sign + by holding down the Shift key with your left-hand pinky finger and pressing the = key with your right-hand pinky finger.

There are two final symbols < and > that are used in mathematical formulas. The < is above the , key and the > is above the . key. If you need to type these, press and hold the Shift key with the pinky finger of your left hand, then use your right-hand middle finger (for the < symbol) or your right-hand ring finger (for the > symbol) to press the appropriate key.

You might not see any of these symbols in an average typing speed test, but they can be useful. If you're hoping to qualify for a data entry job, you can practice with an online typing test that focuses on data entry and spreadsheet equations. Right now, take this short typing test to practice the numbers you learned in previous lessons, as well as all of the standard mathematical symbols:

1 + 2 = 3

90 / 10 = 9

75 - 48 = 27

(3 + 4) * (6 - 5) = 12

There are other keys on the keyboard that generally won't be much use during a typing test, but they'll definitely help you in your daily typing practice. These are often referred to as "movement" keys because they help you move quickly around the screen or a page of text. Because these keys can be located in different places depending on the type of keyboard you're using, we'll just talk about them here. Once you locate them on your own keyboard, you can practice using them at any time.

The Tab key is usually located on the left side of the top row of letters on the keyboard, above the Caps Lock key. If you're typing text, pressing the Tab key will insert a block of blank space. If you're in a table, the Tab key moves you to the next cell of the table.

The Page Up and Page Down keys are a quick way to scroll backwards and forward through longer text documents. They do not insert any blank spaces in the text. You'll probably find these two keys on the far right side of the keyboard.

The four arrow keys are usually in the lower right-hand corner of the keyboard. Use these keys to move left, right, up, and down through a block of text without deleting any letters.

The Home and End keys are also on the right-hand side of most keyboards. Depending on the program you're using, pressing the Home key should take you to the beginning of a line of text, and pressing the End key should take you to the end of that line.

There are other keys on most keyboards, but what they do really depends on the computer you're using, the program you're using, or even what you've formatted those keys to do. You should be able to find a free typing test that quizzes you on these keys once you select the program and operating system you're using.

-------------------------------------

*** Typing Lessons 17: Practice Tips and Tricks

Congratulations! You have learned every standard letter, number, and symbol on the standard QWERTY keyboard! Now that you have the basics down, it's time to concentrate on your speed and your accuracy. The more you practice touch typing, the better both will be. Try to set aside time every day to take a typing test. There are many free typing tests available over the internet, but be sure to get one that you can use on your laptop or computer, rather than an app you download on your phone.

If you already spend a lot of time keyboarding online, that's good! But if you've only been typing for casual communication, now's the time to make sure you're being just as careful as you would if you were typing a project for school or work. When you treat every short e-mail as a good way to get typing practice, you'll get into the habit of typing accurately. Once you've conquered any typing errors you've been making, you can work on really increasing your speed.

Take a typing speed test at least once a week. This will help you judge how quickly you're improving. Most online typing tests track your speed and your accuracy separately, and some of them will even give you a graph at the end so that you have visual proof that you're getting better at touch typing.

Remember, if you're taking a typing test and you notice that you have problems with specific keys or finger movements, go back through these typing lessons as often as you need to. A quick five-minute session that lets you concentrate on one or two keystrokes should be enough to keep you moving forward towards typing mastery.

Are you ready for a final typing test? This one is a real challenge, because it uses every single letter, number, and symbol you've learned. That means it's a good way to get some focused typing practice, so bookmark this page and repeat the test frequently.

"Hello!" said Jaqueline. "What's the plan for this weekend? I heard that the zoo is offering a two-for-one discount on tickets; it's just $4.99 for two adults, or $7.50 for a family of four. We can purchase tickets by e-mailing zootix@metrozoo.org or we can buy them at the door."

SMS from Veronica: ETA ~ 3:06PM

[(12x - 5y) * (3x / 8)] + (4^2) = ? That's a complicated equation!

Amazon is now #1 in book sales, and retailers like Barnes & Noble have had to switch to online sales to keep up. If over 70% of book sales these days are for e-books, what will happen to the print publishing industry? Go to http://bookchat.net and join the conversation. Book_Lover_1959 says, "I think people will always want to read printed books, but that might be an `old-fashioned' attitude."

The phrases "four is less than six" and "ten is greater than three" can written with symbols and numbers only, like this: 4 < 6  and  10 > 3

Unless you're a graphic designer, mathematician, or computer programmer, it's not very likely that you'll every need to type the bar (the | symbol) or the backward slash (the \ symbol), and you'll probably only use the curly brackets { and } for emoticons. But learn them anyway!

-------------------------------------

*** Typing Lessons 18: What Next?

Each typing test contained in this series of typing lessons can be used for a quick review, especially when you're working on the symbols that aren't used as often. That's because many of these infrequently-used symbols aren't included in the average online typing test. To make sure you're getting the most benefit out of your typing practice, find a text selection like the one we gave you in the free typing test at the end of Lesson 17 that uses all (or at least most) of the symbols, numbers, and letters on the keyboard.

After you've improved your accuracy, you can work on your speed. Remember, it might be fun to get a score of 125wpm on a typing speed test, but if you've made a lot of errors, you really aren't touch typing correctly. Try to keep your accuracy rate at 90% or better while you're focusing on increasing your typing speed.

Simply spending time keyboarding online is one of the easiest ways to get your typing practice! As long as you're just as careful to avoid errors, you can treat every keyboard session as a typing test by concentrating on making as few mistakes as possible while still typing at a good speed.

Some people think that they just don't have time in their day to do even half an hour of typing practice, but there are ways to use everyday tasks to do some typing. Here are some suggestions:

If you have something you need to read online, open up a document window and type what you're reading into that document, as you're reading it. Keep your eyes on the page you're reading, not the page you're typing, and don't try to correct any typing mistakes. At the end, compare the original text you read with the text you typed. This exercise works best with short text passages - don't try to re-type your college textbooks!
Look for an online game that acts as a typing test, rather than playing yet another round of Farmville or Candy Crush. There are a lot of fun games that require you to type in letters and words in order to score points. You'll get a lot better at both speed and accuracy when you practice with games like these.
Before you open up your e-mail or your internet browser in the morning, take the first 5 minutes of your online keyboarding time to run through a quick typing test, like one of the ones included in these typing lessons. This will give you at least 30 minutes of typing practice each week.
 

And that's it! You're now on the way to become a skilled touch typist. Keep practicing and keep typing, and you'll keep improving as a typist. We hope you enjoyed these lessons!

-------------------------------------
